- name: Start explorer statistics
  hosts: explorer
  gather_facts: true
  serial: 20
  tasks:
    - name: Start Eth2 explorer statistics
      docker_container:
        name: "{{ explorer_stats_container_name }}"
        state: started
        image: "{{ explorer_image_name }}"
        pull: true
        restart_policy: unless-stopped
        network_mode: bridge
        networks:
          - name: "{{explorer_docker_network_name}}"
            ipv4_address: "172.1.1.104"
        restart: "{{ explorer_stats_require_restart | default(false) }}"
        command: "{{ explorer_stats_start_args }}"
        volumes: "{{explorer_stats_volumes}}"