el_client_name: geth
el_image_name: ethereum/client-go:v1.10.23
execution_endpoint: http://127.0.0.1:{{el_engine_snoop_port}}
snoop_command: "./json_rpc_snoop -p {{el_engine_snoop_port}} http://127.0.0.1:{{el_engine_port}}"

home_dir: "/home/{{ansible_user}}"

el_github_external_user_pubkeys:
  - mariusVanDerWijden
  - holiman
  - karalabe

# bare websocket
elendpoint_ws: ws://127.0.0.1:8546

el_volumes:
  - "{{el_node_dir}}:/eldata"
  - "{{testnet_dir}}:/networkdata"
  - "{{home_dir}}/jwtsecret:/jwtsecret"

geth_init_args: >
  --datadir=/eldata init /networkdata/genesis.json


el_start_args: >
  --datadir=/eldata
  --networkid={{chainID}}
  --http --http.api "admin,engine,net,eth"
  --http.port {{el_rpc_port}}
  --http.addr 0.0.0.0
  --http.corsdomain "*"
  --ws --ws.api "net,eth,engine"
  --ws.port={{el_ws_rpc_port}}
  --ws.addr 0.0.0.0
  --authrpc.port={{el_engine_port}}
  --authrpc.addr=0.0.0.0
  --authrpc.vhosts="*"
  --authrpc.jwtsecret=/jwtsecret
  --nat extip:{{ansible_host}}
  --allow-insecure-unlock
  --metrics --pprof --pprof.addr 0.0.0.0 --pprof.port={{el_metrics_port}}
  --maxpeers=75
  --syncmode=full
  --verbosity {{ {"off": "0", "error": "1", "warn": "2", "info": "3", "debug": "4", "trace": "5", "all": "5"}[execution_log_level] }}
  --vmodule=rpc={{- {"off": "0", "error": "1", "warn": "2", "info": "3", "debug": "4", "trace": "5", "all": "5"}[execution_log_level] }}
  {% if (ethstats_enabled) %}
  --ethstats={{inventory_hostname}}:{{ethstats_password}}@{{ethstats_url}}
  {% endif %}
  {% if (el_bootnode_enode is defined) and el_bootnode_enode %}
  --bootnodes "{{ el_bootnode_enode | join(',') }}"
  {% endif %}

el_user_id: "1000:1000"

# ./go-ethereum/build/bin/geth --datadir=./goerli-shadow-fork init genesis.json
# ./go-ethereum/build/bin/geth --authrpc.jwtsecret=/home/devops/jwtsecret --datadir=./goerli-shadow-fork --ethash.dagdir=./goerli-shadow-fork/ethash --mine --miner.threads=1 --miner.etherbase=0xfb969eb20eca70c2800103bbb0d3757bc60f918a --http --http.corsdomain='*' --http.addr="0.0.0.0" --http.api="engine,net,eth,debug,txpool"  --nat extip:164.90.177.4 --networkid=5 console
# ./go-ethereum/build/bin/geth --datadir=./goerli-shadow-fork --ethash.dagdir=./goerli-shadow-fork/ethash  --http --http.corsdomain='*' --http.addr="0.0.0.0" --http.vhosts="*" --http.api="engine,net,eth,debug,txpool" --ws --ws.api="eth,net,engine" --ws.port=8546 --ws.addr="0.0.0.0" --rpc.allow-unprotected-txs  --nat extip:164.90.177.4 --networkid=5 console
