##############################################
# image name and image location
##############################################
cl_client_name: lighthouse

beacon_image_name: sigp/lighthouse:v3.1.0
validator_image_name: sigp/lighthouse:v3.1.0
beacon_endpoint: "http://127.0.0.1:{{beacon_api_port}}"

cl_github_external_user_pubkeys:
  - AgeManning
  - ethdreamer
  - paulhauner
  - pawanjay176

##############################################
# volume mappings on remote host
##############################################
beacon_volumes:
  - "{{beacon_node_dir}}:/beacondata"
  - "{{testnet_dir}}:/custom_config_data"
  - "{{home_dir}}/jwtsecret:/jwtsecret"

validator_volumes:
  - "{{validator_node_dir}}:/validatordata"
  - "{{testnet_dir}}:/custom_config_data"

##############################################
# arguments to run the containers with
##############################################
beacon_start_args: >
  lighthouse
  --debug-level="{{ beacon_log_level | lower }}"
  --datadir "/beacondata"
  --testnet-dir="/custom_config_data"
  bn
  --disable-enr-auto-update
  --enr-address={{ansible_host}}
  --enr-tcp-port={{beacon_p2p_port}} --enr-udp-port={{beacon_p2p_port}}
  --port={{beacon_p2p_port}} --discovery-port={{beacon_p2p_port}}
  --el
  {% if (bootnode_enrs is defined) and bootnode_enrs %}
  --boot-nodes="{{ bootnode_enrs | join(',') }}"
  {% endif %}  --http
  --http-address=0.0.0.0
  --http-port="{{beacon_api_port}}"
  --metrics
  --metrics-address=0.0.0.0
  --metrics-port="{{beacon_metrics_port}}"
  --listen-address=0.0.0.0
  --graffiti="{{graffiti}}"
  --target-peers={{hi_peer_count}}
  --http-allow-sync-stalled
  --disable-packet-filter
  --execution-endpoint={{execution_endpoint}}
  --suggested-fee-recipient={{fee_recipient}}
  --jwt-secrets="/jwtsecret"
  --count-unrealized
  {% if mev_boost == 'true' %}
  --builder="http://127.0.0.1:{{mev_boost_port}}"
  {% endif %}
# in case of el deposit endpoint problems: --dummy-el

validator_start_args: >
  lighthouse
  --testnet-dir="/custom_config_data"
  vc
  --validators-dir="/validatordata/validators"
  --secrets-dir="/validatordata/secrets"
  --init-slashing-protection
  --server={{beacon_endpoint}}
  --graffiti="{{graffiti}}"
  --http --http-port={{validator_rpc_port}}
  --metrics --metrics-address 0.0.0.0 --metrics-port "{{validator_metrics_port}}"
  --suggested-fee-recipient={{fee_recipient}}
  {% if mev_boost == 'true' %}
  --builder-proposals
  {% endif %}

##############################################
# file permissions and user ids
##############################################
keystores_file_mode: "0700"
beacon_user_id: "1000:1000"
validator_user_id: "0:0"

beacon_log_level: debug
separate_validator_process_enabled: true
